version: "3"

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    # volumes:
    #   - dbdata:/var/lib/mysql
    ports:
      - 3309:3306
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis_boot
    hostname: redis_boot
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/var/lib/redis/
      - ./redis/logs:/var/log/redis/
    ports:
      - 6379:6379
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: spring-boot
    depends_on:
      - mysql
      - redis
  
  front:
    build:
      context: ./frontend/planto
      dockerfile: Dockerfile
    container_name: "react"
    working_dir: "/app/front"
    ports:
      - 3000:3000
    
  mosquitto:
    restart: always
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./eclipse-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./eclipse-mosquitto/data:/mosquitto/data
      - ./eclipse-mosquitto/log:/mosquitto/log
      # - /${USER_DIR}/${MOSQUITTO_DIR}/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # - /${USER_DIR}/${MOSQUITTO_DIR}/data:/mosquitto/data
      # - /${USER_DIR}/${MOSQUITTO_DIR}/log:/mosquitto/log

  my-jenkins:
    image: jenkins/jenkins:lts
    container_name: "my-jenkins"
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - /home/opendocs/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root 
  
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: myweb-proxy
    depends_on:
      - backend
      - front
      