version: "3"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: spring-boot
  
  front:
    build:
      context: ./frontend/planto
      dockerfile: Dockerfile
    container_name: "react"
    working_dir: "/app/front"
    ports:
      - 3000:3000
  
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: myweb-proxy
    depends_on:
      - backend
      - front
      